### ISSUE TITLE
A leader must check whether it has been deposed before processing a read-only request 

### ISSUE THREAD

**Issue by gitanuj** [aviral26/no-free-lunch#6]
Its information may be stale if a more recent leader has been elected. Raft handles this by having the leader exchange heartbeat messages with a majority of the cluster before responding to read-only requests.

**Comment by gitanuj** [comment]
Also, read-only requests should be handled by leader only.

**Comment by aviral26** [comment]
If a new leader has been elected, our client will know about it before making a request to the cluster. Doesn't that address the first comment?
We can address the second one easily.

**Comment by gitanuj** [comment]
Consider the following scenario:
Assuming 3 servers S1, S2 & S3
1. Client connects to S1, gets S2 as leader
2. S1 times out, starts election, S3 votes it and S1 becomes a leader. (S2 doesn't hear abt anything)
3. S1 can now make state changes (assuming concurrent clients)
4. Our client now connects to S2 (which still thinks it's a leader)
5. Client might get stale data

**Comment by aviral26** [comment]
I think our assumption is that the network is reliable, so S1 won't timeout unless S2 crashes.

**Comment by gitanuj** [comment]
Well this is part of the client side of the protocol. Not sure if we need to implement this too!

**Comment by aviral26** [comment]
Addressed in c7915f990de09d23b58fbc78a400aa3bbea46b73

**Comment by aviral26** [comment]
Addressed in c7915f990de09d23b58fbc78a400aa3bbea46b73?

**Comment by gitanuj** [comment]
Fixed with #10
